// AI工具数据库
const AI_TOOLS = [
  // ========== 对话/写作类 ==========
  {
    id: 1,
    name: "ChatGPT",
    name_en: "ChatGPT",
    category: "conversation",
    categoryName: "AI对话",
    icon: "🤖",
    description: "OpenAI开发的AI对话助手，GPT-4模型，支持多轮对话、代码编写、内容创作等。",
    shortDesc: "最通用的AI对话助手",
    price: "免费/Plus $20/月",
    priceLevel: 3,
    rating: 4.9,
    reviews: 12580,
    features: ["多轮对话", "代码编写", "内容创作", "插件生态", "联网搜索"],
    pros: ["通用性强", "生态完善", "持续更新", "社区活跃"],
    cons: ["需要科学上网", "免费版限制多", "中文能力一般"],
    url: "https://chat.openai.com",
    affiliateUrl: "",
    tags: ["对话", "写作", "编程", "通用"],
    badge: "最热门",
    isHot: true,
    isNew: false,
    isFree: true,
    isRecommended: true
  },
  {
    id: 2,
    name: "Claude",
    name_en: "Claude",
    category: "conversation",
    categoryName: "AI对话",
    icon: "🧠",
    description: "Anthropic开发的AI助手，支持20万字超长上下文，擅长长文写作、代码分析和复杂推理。",
    shortDesc: "超长上下文，写作更强",
    price: "免费/Pro $20/月",
    priceLevel: 3,
    rating: 4.8,
    reviews: 8960,
    features: ["20万字上下文", "长文写作", "代码分析", "文档处理", "图片理解"],
    pros: ["长文本处理强", "写作更自然", "安全性高", "中文支持好"],
    cons: ["插件较少", "联网功能不稳定", "创意能力一般"],
    url: "https://claude.ai",
    affiliateUrl: "",
    tags: ["对话", "写作", "长文本", "分析"],
    badge: "长文本之王",
    isHot: true,
    isNew: false,
    isFree: true,
    isRecommended: true
  },
  {
    id: 3,
    name: "Kimi",
    name_en: "Kimi",
    category: "conversation",
    categoryName: "AI对话",
    icon: "🌙",
    description: "月之暗面开发的国产AI助手，支持20万字上下文，完全免费，中文能力强。",
    shortDesc: "国产AI，20万字免费用",
    price: "免费",
    priceLevel: 0,
    rating: 4.7,
    reviews: 15670,
    features: ["20万字上下文", "读取PDF/链接", "中文优化", "免费使用", "联网搜索"],
    pros: ["完全免费", "中文优秀", "长文本强", "无需翻墙"],
    cons: ["不支持图片生成", "复杂推理一般"],
    url: "https://kimi.moonshot.cn",
    affiliateUrl: "",
    tags: ["对话", "国产", "免费", "长文本"],
    badge: "国产之光",
    isHot: true,
    isNew: false,
    isFree: true,
    isRecommended: true
  },
  {
    id: 4,
    name: "讯飞星火",
    name_en: "iFlytek Spark",
    category: "conversation",
    categoryName: "AI对话",
    icon: "🔮",
    description: "科大讯飞出品的大模型，中文语音能力强，适合办公场景，免费使用。",
    shortDesc: "语音能力强，办公助手",
    price: "免费",
    priceLevel: 0,
    rating: 4.5,
    reviews: 6540,
    features: ["语音交互", "办公助手", "多模态", "中文优化", "免费使用"],
    pros: ["语音能力突出", "办公场景优化", "完全免费", "无需翻墙"],
    cons: ["长文本能力一般", "国际功能有限"],
    url: "https://xinghuo.xfyun.cn",
    affiliateUrl: "",
    tags: ["对话", "国产", "免费", "办公"],
    badge: "",
    isHot: false,
    isNew: false,
    isFree: true,
    isRecommended: false
  },
  {
    id: 5,
    name: "通义千问",
    name_en: "Tongyi Qianwen",
    category: "conversation",
    categoryName: "AI对话",
    icon: "🎯",
    description: "阿里云出品的大模型，中文能力强，支持多模态，免费使用。",
    shortDesc: "阿里出品，多模态支持",
    price: "免费",
    priceLevel: 0,
    rating: 4.6,
    reviews: 7890,
    features: ["多模态", "中文优化", "代码能力", "创意写作", "免费使用"],
    pros: ["阿里生态", "多模态强", "免费使用", "稳定可靠"],
    cons: ["长文本一般", "英文能力有限"],
    url: "https://qwen.ai",
    affiliateUrl: "",
    tags: ["对话", "国产", "免费", "多模态"],
    badge: "",
    isHot: false,
    isNew: false,
    isFree: true,
    isRecommended: false
  },
  {
    id: 6,
    name: "文心一言",
    name_en: "ERNIE Bot",
    category: "conversation",
    categoryName: "AI对话",
    icon: "📝",
    description: "百度出品的大模型，中文理解能力强，文生图能力出色，免费使用。",
    shortDesc: "百度大模型，文图兼备",
    price: "免费",
    priceLevel: 0,
    rating: 4.5,
    reviews: 12340,
    features: ["文生图", "中文理解", "知识问答", "创意写作", "免费使用"],
    pros: ["文生图能力强", "百度生态", "完全免费", "中文优化"],
    cons: ["复杂推理一般", "开放度有限"],
    url: "https://yiyan.baidu.com",
    affiliateUrl: "",
    tags: ["对话", "国产", "免费", "绘图"],
    badge: "",
    isHot: false,
    isNew: false,
    isFree: true,
    isRecommended: false
  },

  // ========== 图像生成类 ==========
  {
    id: 10,
    name: "Midjourney",
    name_en: "Midjourney",
    category: "image",
    categoryName: "AI绘图",
    icon: "🎨",
    description: "最强大的AI图像生成工具之一，生成质量极高，创意性强，适合艺术创作和商业设计。",
    shortDesc: "最强AI绘图，质量顶尖",
    price: "$30/月起",
    priceLevel: 4,
    rating: 4.9,
    reviews: 19870,
    features: ["文生图", "图生图", "风格多样", "高清输出", "社区参考"],
    pros: ["质量最高", "风格丰富", "社区活跃", "持续更新"],
    cons: ["需要科学上网", "价格较高", "速度较慢", "版权争议"],
    url: "https://midjourney.com",
    affiliateUrl: "",
    tags: ["绘图", "艺术", "商业", "高质量"],
    badge: "质量最佳",
    isHot: true,
    isNew: false,
    isFree: false,
    isRecommended: true
  },
  {
    id: 11,
    name: "Stable Diffusion",
    name_en: "Stable Diffusion",
    category: "image",
    categoryName: "AI绘图",
    icon: "⚡",
    description: "开源免费的AI绘图模型，本地部署可控性强，生态丰富，适合进阶用户。",
    shortDesc: "开源免费，本地可控",
    price: "免费/本地部署",
    priceLevel: 0,
    rating: 4.7,
    reviews: 15670,
    features: ["开源免费", "本地部署", "高度可控", "模型众多", "LoRA定制"],
    pros: ["完全免费", "本地运行", "高度定制", "社区丰富"],
    cons: ["硬件要求高", "学习曲线陡", "需要调试"],
    url: "https://stability.ai",
    affiliateUrl: "",
    tags: ["绘图", "开源", "免费", "本地"],
    badge: "开源之选",
    isHot: true,
    isNew: false,
    isFree: true,
    isRecommended: true
  },
  {
    id: 12,
    name: "DALL-E 3",
    name_en: "DALL-E 3",
    category: "image",
    categoryName: "AI绘图",
    icon: "🖼️",
    description: "OpenAI出品的AI绘图工具，与ChatGPT深度集成，生成准确度高，操作简单。",
    shortDesc: "OpenAI出品，集成ChatGPT",
    price: "$20/月(Plus用户)",
    priceLevel: 3,
    rating: 4.8,
    reviews: 8760,
    features: ["文生图", "ChatGPT集成", "文字生成", "语义理解强", "版权清晰"],
    pros: ["准确度高", "集成方便", "版权无忧", "易用性好"],
    cons: ["需要Plus订阅", "风格有限制", "速度一般"],
    url: "https://openai.com/dall-e-3",
    affiliateUrl: "",
    tags: ["绘图", "集成", "易用"],
    badge: "",
    isHot: true,
    isNew: false,
    isFree: false,
    isRecommended: true
  },
  {
    id: 13,
    name: "Bing Image Creator",
    name_en: "Bing Image Creator",
    category: "image",
    categoryName: "AI绘图",
    icon: "🔍",
    description: "微软必应出品的免费AI绘图工具，基于DALL-E 3，完全免费且无需特殊网络。",
    shortDesc: "免费DALL-E3，无需翻墙",
    price: "免费",
    priceLevel: 0,
    rating: 4.6,
    reviews: 12340,
    features: ["免费使用", "DALL-E 3", "无需翻墙", "速度较快", "积分制"],
    pros: ["完全免费", "质量高", "无需翻墙", "微软账号即可"],
    cons: ["每日额度限制", "服务器不稳定", "无高级控制"],
    url: "https://bing.com/create",
    affiliateUrl: "",
    tags: ["绘图", "免费", "国产可用"],
    badge: "免费之选",
    isHot: true,
    isNew: false,
    isFree: true,
    isRecommended: true
  },
  {
    id: 14,
    name: "通义万相",
    name_en: "Tongyi Wanxiang",
    category: "image",
    categoryName: "AI绘图",
    icon: "🌈",
    description: "阿里云出品的AI绘图工具，中文提示词优化，完全免费使用。",
    shortDesc: "阿里绘图，中文友好",
    price: "免费",
    priceLevel: 0,
    rating: 4.5,
    reviews: 6540,
    features: ["中文优化", "多种风格", "免费使用", "阿里云集成", "API支持"],
    pros: ["中文提示词好", "完全免费", "无需翻墙", "稳定性好"],
    cons: ["质量一般", "风格有限"],
    url: "https://wanx.alibaba.com",
    affiliateUrl: "",
    tags: ["绘图", "国产", "免费"],
    badge: "",
    isHot: false,
    isNew: false,
    isFree: true,
    isRecommended: false
  },
  {
    id: 15,
    name: "Leonardo.ai",
    name_en: "Leonardo.ai",
    category: "image",
    categoryName: "AI绘图",
    icon: "🎭",
    description: "功能强大的AI绘图平台，每日赠送免费额度，风格多样，社区活跃。",
    shortDesc: "每日免费，风格多样",
    price: "免费额度+付费",
    priceLevel: 2,
    rating: 4.7,
    reviews: 9870,
    features: ["每日免费额度", "风格控制", "社区参考", "模型训练", "API支持"],
    pros: ["免费额度", "控制力强", "社区活跃", "功能丰富"],
    cons: ["免费有限", "界面复杂", "速度一般"],
    url: "https://leonardo.ai",
    affiliateUrl: "",
    tags: ["绘图", "社区", "控制"],
    badge: "",
    isHot: false,
    isNew: false,
    isFree: true,
    isRecommended: false
  },

  // ========== 编程类 ==========
  {
    id: 20,
    name: "GitHub Copilot",
    name_en: "GitHub Copilot",
    category: "coding",
    categoryName: "AI编程",
    icon: "💻",
    description: "微软/GitHub出品的AI编程助手，代码补全强大，支持多种语言和IDE。",
    shortDesc: "代码补全神器，开发者必备",
    price: "$10/月（学生免费）",
    priceLevel: 3,
    rating: 4.8,
    reviews: 23450,
    features: ["代码补全", "多语言支持", "IDE集成", "注释生成", "错误检测"],
    pros: ["补全准确", "支持广泛", "学生免费", "微软生态"],
    cons: ["需要付费", "复杂逻辑一般", "依赖IDE"],
    url: "https://github.com/features/copilot",
    affiliateUrl: "",
    tags: ["编程", "代码补全", "开发者"],
    badge: "开发者必备",
    isHot: true,
    isNew: false,
    isFree: false,
    isRecommended: true
  },
  {
    id: 21,
    name: "Codeium",
    name_en: "Codeium",
    category: "coding",
    categoryName: "AI编程",
    icon: "⚡",
    description: "完全免费的AI编程助手，支持所有主流IDE，代码补全快速准确。",
    shortDesc: "完全免费的Copilot替代",
    price: "免费",
    priceLevel: 0,
    rating: 4.6,
    reviews: 8760,
    features: ["代码补全", "完全免费", "多IDE支持", "多语言", "搜索增强"],
    pros: ["完全免费", "无使用限制", "支持广泛", "轻量快速"],
    cons: ["补全能力不如Copilot", "功能相对简单"],
    url: "https://codeium.com",
    affiliateUrl: "",
    tags: ["编程", "免费", "补全"],
    badge: "免费首选",
    isHot: true,
    isNew: false,
    isFree: true,
    isRecommended: true
  },
  {
    id: 22,
    name: "Cursor",
    name_en: "Cursor",
    category: "coding",
    categoryName: "AI编程",
    icon: "🎯",
    description: "AI First的代码编辑器，内置ChatGPT，可以直接聊天修改代码，适合AI辅助编程。",
    shortDesc: "AI优先的代码编辑器",
    price: "免费版/Pro $20/月",
    priceLevel: 1,
    rating: 4.7,
    reviews: 5430,
    features: ["AI对话编程", "直接修改代码", "智能补全", "代码理解", "多语言"],
    pros: ["AI深度集成", "操作直观", "免费版可用", "迭代快"],
    cons: ["编辑器功能有限", "生态不如VSCode"],
    url: "https://cursor.sh",
    affiliateUrl: "",
    tags: ["编程", "编辑器", "AI"],
    badge: "创新之作",
    isHot: true,
    isNew: true,
    isFree: true,
    isRecommended: true
  },

  // ========== 视频类 ==========
  {
    id: 30,
    name: "Sora",
    name_en: "Sora",
    category: "video",
    categoryName: "AI视频",
    icon: "🎬",
    description: "OpenAI发布的AI视频生成模型，可生成60秒高清视频，效果惊艳但尚未公开。",
    shortDesc: "OpenAI视频生成，效果惊人",
    price: "待定",
    priceLevel: 4,
    rating: 4.9,
    reviews: 25670,
    features: ["60秒视频", "高清画质", "复杂场景", "物理模拟", "多风格"],
    pros: ["效果最强", "OpenAI背书", "能力全面", "持续更新"],
    cons: ["尚未公开", "预计价格高", "需要等待"],
    url: "https://openai.com/sora",
    affiliateUrl: "",
    tags: ["视频", "前沿", "OpenAI"],
    badge: "未发布",
    isHot: true,
    isNew: true,
    isFree: false,
    isRecommended: false
  },
  {
    id: 31,
    name: "Runway",
    name_en: "Runway",
    category: "video",
    categoryName: "AI视频",
    icon: "🎥",
    description: "专业级AI视频工具，支持文生视频、图生视频、视频风格迁移等功能。",
    shortDesc: "专业视频AI，功能全面",
    price: "$12/月起",
    priceLevel: 3,
    rating: 4.6,
    reviews: 7890,
    features: ["文生视频", "图生视频", "风格迁移", "运镜控制", "绿幕抠像"],
    pros: ["功能丰富", "专业程度高", "持续更新", "教程完善"],
    cons: ["价格较高", "需要科学上网", "免费额度有限"],
    url: "https://runwayml.com",
    affiliateUrl: "",
    tags: ["视频", "专业"],
    badge: "",
    isHot: false,
    isNew: false,
    isFree: false,
    isRecommended: false
  },
  {
    id: 32,
    name: "Pika",
    name_en: "Pika",
    category: "video",
    categoryName: "AI视频",
    icon: "✨",
    description: "新兴的AI视频生成工具，操作简单，对新手友好，生成速度快。",
    shortDesc: "新手友好，快速出片",
    price: "免费额度+付费",
    priceLevel: 2,
    rating: 4.5,
    reviews: 4320,
    features: ["文生视频", "操作简单", "生成快速", "社区活跃", "风格多样"],
    pros: ["易上手", "速度快", "社区支持", "持续更新"],
    cons: ["质量不如Runway", "免费有限", "功能有限"],
    url: "https://pika.art",
    affiliateUrl: "",
    tags: ["视频", "新手"],
    badge: "新手推荐",
    isHot: true,
    isNew: true,
    isFree: true,
    isRecommended: true
  },

  // ========== 办公类 ==========
  {
    id: 40,
    name: "Notion AI",
    name_en: "Notion AI",
    category: "productivity",
    categoryName: "效率办公",
    icon: "📓",
    description: "集成在Notion笔记工具中的AI助手，适合边写边整理知识，提升写作效率。",
    shortDesc: "笔记+AI，效率加倍",
    price: "$10/月",
    priceLevel: 3,
    rating: 4.5,
    reviews: 8760,
    features: ["智能续写", "自动总结", "语法纠错", "翻译", "模板生成"],
    pros: ["深度集成", "操作便捷", "适合笔记场景", "团队协作"],
    cons: ["需要Notion订阅", "功能有限", "不适合复杂任务"],
    url: "https://notion.so",
    affiliateUrl: "",
    tags: ["办公", "笔记", "协作"],
    badge: "",
    isHot: false,
    isNew: false,
    isFree: false,
    isRecommended: false
  },
  {
    id: 41,
    name: "Gamma",
    name_en: "Gamma",
    category: "productivity",
    categoryName: "效率办公",
    icon: "📊",
    description: "AI驱动的新一代演示文稿工具，输入主题即可生成精美PPT，适合商业演示。",
    shortDesc: "AI生成PPT，告别加班",
    price: "免费版/Pro $12/月",
    priceLevel: 2,
    rating: 4.6,
    reviews: 6540,
    features: ["AI生成PPT", "精美模板", "一键生成", "多人协作", "多种格式导出"],
    pros: ["质量高", "速度快", "模板精美", "协作方便"],
    cons: ["免费功能有限", "定制化受限", "需要联网"],
    url: "https://gamma.app",
    affiliateUrl: "",
    tags: ["办公", "PPT", "演示"],
    badge: "",
    isHot: true,
    isNew: false,
    isFree: true,
    isRecommended: true
  },
  {
    id: 42,
    name: "WPS AI",
    name_en: "WPS AI",
    category: "productivity",
    categoryName: "效率办公",
    icon: "📄",
    description: "金山WPS集成的AI助手，中文办公场景优化，支持文档、表格、演示。",
    shortDesc: "国产办公AI，无缝集成",
    price: "免费",
    priceLevel: 0,
    rating: 4.4,
    reviews: 9870,
    features: ["文档处理", "表格分析", "PPT生成", "中文优化", "免费使用"],
    pros: ["无缝集成WPS", "中文优化", "完全免费", "无需额外软件"],
    cons: ["功能相对基础", "AI能力有限"],
    url: "https://ai.wps.cn",
    affiliateUrl: "",
    tags: ["办公", "国产", "免费"],
    badge: "",
    isHot: false,
    isNew: false,
    isFree: true,
    isRecommended: false
  },

  // ========== 其他工具 ==========
  {
    id: 50,
    name: "Perplexity",
    name_en: "Perplexity",
    category: "search",
    categoryName: "AI搜索",
    icon: "🔮",
    description: "AI驱动的搜索引擎，可以实时获取信息并给出带来源的答案，适合研究和探索。",
    shortDesc: "AI搜索，研究利器",
    price: "免费/Pro $20/月",
    priceLevel: 1,
    rating: 4.7,
    reviews: 12340,
    features: ["AI搜索", "实时信息", "来源标注", "追问深入", "追问扩展"],
    pros: ["信息准确", "来源可靠", "适合研究", "速度快"],
    cons: ["复杂问题一般", "免费版有限制"],
    url: "https://perplexity.ai",
    affiliateUrl: "",
    tags: ["搜索", "研究", "信息"],
    badge: "",
    isHot: true,
    isNew: false,
    isFree: true,
    isRecommended: true
  },
  {
    id: 51,
    name: "New Bing",
    name_en: "New Bing",
    category: "search",
    categoryName: "AI搜索",
    icon: "🌐",
    description: "微软必应集成的AI搜索功能，可以实时获取信息，支持对话式搜索。",
    shortDesc: "微软AI搜索，集成Edge",
    price: "免费",
    priceLevel: 0,
    rating: 4.5,
    reviews: 15670,
    features: ["AI对话", "实时搜索", "Edge集成", "图片理解", "免费使用"],
    pros: ["完全免费", "微软生态", "集成方便", "无需翻墙（部分）"],
    cons: ["需要Edge浏览器", "地区限制"],
    url: "https://bing.com",
    affiliateUrl: "",
    tags: ["搜索", "免费", "微软"],
    badge: "",
    isHot: false,
    isNew: false,
    isFree: true,
    isRecommended: false
  }
];

// 工具分类
const CATEGORIES = [
  { id: "all", name: "全部工具", icon: "🔧", count: AI_TOOLS.length },
  { id: "conversation", name: "AI对话", icon: "💬", count: AI_TOOLS.filter(t => t.category === 'conversation').length },
  { id: "image", name: "AI绘图", icon: "🖼️", count: AI_TOOLS.filter(t => t.category === 'image').length },
  { id: "coding", name: "AI编程", icon: "💻", count: AI_TOOLS.filter(t => t.category === 'coding').length },
  { id: "video", name: "AI视频", icon: "🎬", count: AI_TOOLS.filter(t => t.category === 'video').length },
  { id: "productivity", name: "效率办公", icon: "⚡", count: AI_TOOLS.filter(t => t.category === 'productivity').length },
  { id: "search", name: "AI搜索", icon: "🔍", count: AI_TOOLS.filter(t => t.category === 'search').length }
];

// 导出
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { AI_TOOLS, CATEGORIES };
}